
repos:
  # ----------------------------------
  # Basic hygiene
  # ----------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict

  # ----------------------------------
  # Ruff (linting + optional fixes)
  # ----------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
  # ----------------------------------
  # Black (formatter)
  # ----------------------------------
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--check"]
  # ----------------------------------
  # mypy (type checking)
  # ----------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy

  # ----------------------------------
  # pydocstyle (docs checking)
  # ----------------------------------
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0 # Use the desired version tag or hash
  #   hooks:
  #     - id: pydocstyle
